apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: you@skydata.space
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-production-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: skydata-379820