controller:
  service:
    type: LoadBalancer  # Явно указываем тип
    externalTrafficPolicy: Local
    # Убираем аннотацию Internal, чтобы получить внешний IP
  ingressClassResource:
    name: nginx  # Соответствует ingressClassName в argocd
    default: true  # Делаем этот класс дефолтным
  publishService:
    enabled: true  # Для передачи IP в Ingress