apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx  # Удалённый репозиторий Helm
    targetRevision: 4.12.1                       # Версия чарта
    chart: ingress-nginx                         # Название чарта
    helm:
      releaseName: ingress-nginx
      valuesFiles:
        - https://github.com/SkyTornado/gitops-skydata.git/raw/main/manifests/ingress-nginx/values.yaml  # Полный путь к values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true