apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.1
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
          ingressClassResource:
            name: nginx
            default: true
          publishService:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true