apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/7.8.14/templates/argocd-application-controller.yaml
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.8.14
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml