server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argo.skydata.space  # Добавляем это поле
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argo.skydata.space
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - argo.skydata.space
    tls:
      - hosts:
          - argo.skydata.space
        secretName: argocd-server-tls
  configs:
    params:
      server.insecure: false