apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.16.0  # Последняя версия из kubernetes-sigs
    chart: external-dns
    helm:
      releaseName: external-dns
      values: |
        provider:
          name: google
        google:
          project: skydata-379820
          serviceAccountSecret: external-dns-sa
        domainFilters:
          - skydata.space
        logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true