apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.7.8  # Последняя версия Bitnami
    chart: external-dns
    helm:
      releaseName: external-dns
      values: |
        provider: google
        google:
          project: skydata-379820
          serviceAccountKeySecretRef:
            name: external-dns-sa
            key: credentials.json
        domainFilters:
          - skydata.space
        logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true