apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: skydata
  namespace: argocd
spec:
  description: Skydata project for managing GKE cluster applications
  sourceRepos:
    - https://github.com/SkyTornado/gitops-skydata.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true