apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.14
      chart: argo-cd
      helm:
        releaseName: argocd
        valueFiles:
          - $values/manifests/argocd/values.yaml  # Ссылка на второй source
    - repoURL: https://github.com/SkyTornado/gitops-skydata.git
      targetRevision: main
      ref: values  # Псевдоним для ссылки в valueFiles
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true