apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SkyTornado/gitops-skydata.git
    targetRevision: main
    path: manifests/argocd
    kustomize:
      helm: true  # Включаем поддержку Helm в Kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # На случай, если namespace ещё не создан