apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.15.1
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
        installCRDs: false
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: cert-manager-stage-skydata-gke@skydata-379820.iam.gserviceaccount.com
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true