apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    version: 8.7.8
    releaseName: external-dns
    namespace: kube-system
    valuesFile: values.yaml